name: MLOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  data-preparation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Prepare data
        run: python src/data_preparation.py
      - name: Validate data
        run: pytest tests/test_data.py

  train-model:
    runs-on: ubuntu-latest
    needs: data-preparation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Train model
        run: |
          python src/train.py
          python src/evaluate.py
      - name: Validate model
        run: pytest tests/test_model.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: |
            models/model.joblib
            results/metrics.txt

  docker-build:
    runs-on: ubuntu-latest
    needs: train-model
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/iris-model:latest

  # Optional: Add deployment to AWS/GCP/Azure
  # monitor:
  #   runs-on: ubuntu-latest
  #   needs: docker-build
  #   steps:
  #     - run: echo "Add monitoring logic here"